title: CAMCAD
description: Child-Centred AI-Mediated Collaborative Agency by Design workshop at CHI 2026
baseurl: /CAMCAD
url: https://oxfordhcc.github.io

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: University of Oxford Child-Centred AI Design Lab (https://oxfordccai.org/)
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
